site_name: GiG Open
theme: 
    name: material
    palette:
        scheme: preference
    logo: assets/images/GiG logo_vector-04.svg
nav:
    - Welcome: index.md
    - Open Source:
        - Using: open-source/using.md
        - Contributing: open-source/contributing.md
        - Forking: open-source/forking.md
        - Creating: open-source/creating.md
    - Projects: projects.md
#   - Open Knowledge: open-knowledge.md
repo_name: GiG/open
repo_url: https://github.com/GiG/open
extra_css:
    - stylesheets/extra.css
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/GiG
      - icon: material/link-variant
        link: https://www.gig.com
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
plugins:
  - search:
        prebuild_index: true
  - git-revision-date-localized
  - minify:
        minify_html: true
