site_name: GiG Open
copyright: GiG Open ($ver)
theme: 
    name: material
    font:
        text: Inter
    palette:
        scheme: preference
    logo: assets/images/GiG logo_vector-04.svg
    custom_dir: overrides
nav:
    - Welcome: index.md
    - Open Source:
        - Using: open-source/using.md
        - Contributing: open-source/contributing.md
        - Forking: open-source/forking.md
        - Creating: open-source/creating.md
    - Projects: projects.md
#   - Open Knowledge: open-knowledge.md
repo_name: GiG/open
repo_url: https://github.com/GiG/open
extra_css:
    - stylesheets/extra.css
extra:
    manifest: site.webmanifest
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/GiG
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/GIG_online
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/company/gig-gaming-innovation-group/
      - icon: material/link-variant
        link: https://gig.com
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
plugins:
  - search:
        prebuild_index: true
  - git-revision-date-localized
  - minify:
        minify_html: true
