site_name: GiG Open
theme: 
    name: material
    palette:
        scheme: preference
        primary: green
        accent: green
    logo: assets/images/GiG logo_vector-04.svg
nav:
    - Open Source:
        - Using: open-source/using.md
        - Contributing: open-source/contributing.md
        - Creating: open-source/creating.md
    - Open Knowledge: open-knowledge.md
    - Projects: projects.md
repo_name: GiG/open
repo_url: https://github.com/GiG/open
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/GiG
      - icon: material/link-variant
        link: https://www.gig.com
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true

